(() => {
'use strict';

const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const $=id=>document.getElementById(id);
const ui={loading:$('loading'),hud:$('hud'),score:$('score'),lives:$('lives'),goalLeft:$('goal-left'),goalFill:$('goal-fill'),tutorial:$('tutorial'),gesture:$('gesture'),damage:$('damage'),toast:$('toast'),home:$('home'),pause:$('pause'),over:$('over'),win:$('win'),finalDistance:$('final-distance'),bestDistance:$('best-distance'),winLives:$('win-lives')};

const VERSION='20260806-readability1';
const ATLAS_SCALE=.35;
const CELL_W=448,CELL_H=336,PLAYER_CELL=213;
const GOAL=1800,MAX_LIVES=5,MAX_Z=100,LANES=[-1,0,1];
const SPRITES={
  ptero_up:[896,336,448,336],ptero_mid:[1344,336,448,336],ptero_glide:[0,672,448,336],
  trex:[448,672,448,336],trex_roar:[896,672,448,336],boulder:[1344,672,448,336],
  log:[0,1008,448,336],thorn:[448,1008,448,336],cactus:[896,1008,448,336],fossil:[1344,1008,448,336]
};
const PLAYER_CELLS={run1:[0,0],run2:[1,0],run3:[2,0],run4:[0,1],turn_left:[1,1],turn_right:[2,1],jump:[0,2],slide:[1,2],hurt:[2,2]};
const PTERO_BLEND_SPEED=4.6;
const obstacleDefs={
  boulder:{action:'up',sprite:'boulder',width:.92,heightScale:1},
  log:{action:'up',sprite:'log',width:.98,heightScale:1},
  thorn:{action:'up',sprite:'thorn',width:.96,heightScale:1},
  cactus:{action:'side',sprite:'cactus',width:.74,heightScale:2.35},
  fossil:{action:'up',sprite:'fossil',width:.96,heightScale:1},
  trex:{action:'side',sprite:'trex',width:1.32,heightScale:2.12},
  ptero:{action:'down',width:1.08,heightScale:1}
};
const tutorialSteps=[{action:'left',type:'trex'},{action:'right',type:'boulder'},{action:'up',type:'log'},{action:'down',type:'ptero'}];
const images={};
function loadImage(name,url){return new Promise((resolve,reject)=>{const im=new Image();im.decoding='async';im.onload=()=>{images[name]=im;resolve(im)};im.onerror=()=>reject(new Error(`No se pudo cargar ${url}`));im.src=url})}
function loadAssets(){return Promise.all([loadImage('atlas',`assets/game-atlas.avif?v=20260801-mega2`),loadImage('player',`assets/raptor-player.avif?v=20260801-phase1`),loadImage('ptero0',`assets/ptero-flight-0.avif?v=${VERSION}`),loadImage('ptero1',`assets/ptero-flight-1.avif?v=${VERSION}`)])}

let savedBest=0;try{savedBest=Number(localStorage.getItem('raptorRushBest')||0)}catch(_){}
let state='loading',w=0,h=0,dpr=1,last=performance.now(),time=0,distance=0,speed=19,lives=MAX_LIVES,best=savedBest,shake=0;
let player={lane:0,x:0,y:0,vy:0,slide:0,hurt:0,invuln:0,turnTimer:0,turnDir:0};
let obstacles=[],spawnTimer=2,tutorialIndex=0,tutorialPaused=false,tutorialObstacle=null,tutorialDelay=.5,audio=null;
let visualDebug={track:null,ptero:null,obstacles:[],background:null};

function tone(freq,dur=.08,type='sine',vol=.025,slide=0){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(40,freq+slide),audio.currentTime+dur);g.gain.value=vol;g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function initAudio(){try{audio||=new(AudioContext||webkitAudioContext)();if(audio.state==='suspended')audio.resume()}catch(_){}}
function resize(){dpr=Math.min(2,devicePixelRatio||1);w=innerWidth;h=innerHeight;const rw=Math.round(w*dpr),rh=Math.round(h*dpr);if(canvas.width!==rw||canvas.height!==rh){canvas.width=rw;canvas.height=rh;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high'}}
function setState(next){state=next;ui.home.classList.toggle('visible',next==='home');ui.pause.classList.toggle('visible',next==='paused');ui.over.classList.toggle('visible',next==='over');ui.win.classList.toggle('visible',next==='won');ui.hud.classList.toggle('hidden',!['running','tutorial'].includes(next));if(next!=='tutorial')hideTutorial()}
function reset(){distance=0;speed=19;lives=MAX_LIVES;shake=0;time=0;player={lane:0,x:0,y:0,vy:0,slide:0,hurt:0,invuln:0,turnTimer:0,turnDir:0};obstacles=[];spawnTimer=999;tutorialIndex=0;tutorialPaused=false;tutorialObstacle=null;tutorialDelay=.45;updateHud()}
function start(){initAudio();reset();setState('running');tone(220,.1,'square',.03,130)}
function pause(){if(state==='running')setState('paused')}
function resume(){if(state==='paused'){last=performance.now();setState('running')}}
function home(){reset();setState('home')}
function finish(next){best=Math.max(best,Math.floor(distance));try{localStorage.setItem('raptorRushBest',best)}catch(_){}ui.finalDistance.textContent=`${Math.floor(distance)} m`;ui.bestDistance.textContent=`${best} m`;setState(next)}
function gameOver(){finish('over');tone(105,.35,'sawtooth',.05,-55)}
function win(){distance=GOAL;updateHud();ui.winLives.textContent=lives;finish('won');tone(440,.16,'square',.04,180);showToast('¡DESIERTO!')}
function updateHud(){ui.score.textContent=`${Math.floor(distance)} m`;ui.goalLeft.textContent=`${Math.max(0,Math.ceil(GOAL-distance))} m`;ui.goalFill.style.width=`${Math.min(100,distance/GOAL*100)}%`;[...ui.lives.children].forEach((e,i)=>e.classList.toggle('lost',i>=lives))}
function showToast(t){ui.toast.textContent=t;ui.toast.classList.remove('show');void ui.toast.offsetWidth;ui.toast.classList.add('show')}
function showTutorial(action){tutorialPaused=true;state='tutorial';ui.gesture.dataset.direction=action;ui.tutorial.classList.add('visible');ui.tutorial.setAttribute('aria-hidden','false');tone(330,.1,'sine',.025,80)}
function hideTutorial(){tutorialPaused=false;ui.tutorial.classList.remove('visible');ui.tutorial.setAttribute('aria-hidden','true')}
function move(dir){if(!['running','tutorial'].includes(state))return false;const old=player.lane;player.lane=Math.max(-1,Math.min(1,player.lane+dir));if(old!==player.lane){player.turnDir=dir;player.turnTimer=.28;tone(210,.045,'sine',.015,dir*35);return true}return false}
function jump(){if(!['running','tutorial'].includes(state)||player.y>.03||player.slide>0)return false;player.vy=6;tone(280,.1,'square',.025,120);return true}
function slide(){if(!['running','tutorial'].includes(state)||player.y>.1)return false;player.slide=.9;tone(105,.09,'sawtooth',.02,-25);return true}
function apply(action){return action==='left'?move(-1):action==='right'?move(1):action==='up'?jump():slide()}
function act(action){if(state==='tutorial'){const step=tutorialSteps[tutorialIndex];if(!step||step.action!==action){tone(100,.06,'square',.025,-20);return}hideTutorial();state='running';apply(action);if(tutorialObstacle)obstacles=obstacles.filter(o=>o!==tutorialObstacle);tutorialIndex++;tutorialObstacle=null;tutorialDelay=1.25;if(tutorialIndex>=tutorialSteps.length){spawnTimer=1.2;showToast('¡LISTO!')}return}if(state==='running')apply(action)}
function spawnTutorial(){const step=tutorialSteps[tutorialIndex];if(!step)return;tutorialObstacle={type:step.type,lane:player.lane,z:68,tutorial:true,hit:false,phase:Math.random()*6};obstacles.push(tutorialObstacle)}
function spawnPattern(){const desert=distance>1100,pool=desert?['cactus','boulder','fossil','ptero','trex']:['boulder','log','thorn','ptero','trex'];const type=pool[Math.floor(Math.random()*pool.length)],lane=LANES[Math.floor(Math.random()*3)];obstacles.push({type,lane,z:MAX_Z+8,hit:false,phase:Math.random()*6});if(Math.random()<.24&&!['trex','fossil','ptero'].includes(type)){const lane2=LANES.filter(x=>x!==lane)[Math.floor(Math.random()*2)];obstacles.push({type:Math.random()<.5?'boulder':'thorn',lane:lane2,z:MAX_Z+22,hit:false,phase:Math.random()*6})}}

function trackAt(p){const q=Math.pow(Math.max(0,Math.min(1,p)),1.18),half=w*(.075+(.49-.075)*q);return{half,laneCenter:half*2/3,laneWidth:half*2/3}}
function perspective(z){const p=1-Math.max(0,Math.min(1,z/MAX_Z)),t=trackAt(p);return{p,y:h*.31+Math.pow(p,1.43)*h*.635,half:t.half,laneX:t.laneCenter,laneWidth:t.laneWidth}}
function safeAgainst(o){const def=obstacleDefs[o.type];if(def.action==='side')return player.lane!==o.lane;if(player.lane!==o.lane)return true;if(def.action==='up')return player.y>.52;if(def.action==='down')return player.slide>.08;return false}
function hit(o){if(player.invuln>0||o.hit)return;o.hit=true;lives--;player.invuln=1.5;player.hurt=.65;shake=13;speed=Math.max(16,speed-3);ui.damage.classList.remove('show');void ui.damage.offsetWidth;ui.damage.classList.add('show');tone(85,.22,'sawtooth',.055,-40);updateHud();showToast(lives>0?`♥ ${lives}`:'SIN VIDAS');if(lives<=0)gameOver()}
function update(dt){if(!['running','tutorial'].includes(state))return;time+=dt;player.x+=(player.lane-player.x)*Math.min(1,dt*10);if(player.y>0||player.vy>0){player.vy-=22*dt;player.y=Math.max(0,player.y+player.vy*dt);if(player.y===0&&player.vy<0)player.vy=0}player.slide=Math.max(0,player.slide-dt);player.invuln=Math.max(0,player.invuln-dt);player.hurt=Math.max(0,player.hurt-dt);player.turnTimer=Math.max(0,player.turnTimer-dt);shake*=Math.pow(.02,dt);if(state==='tutorial')return;distance+=speed*dt;speed=Math.min(31,19+distance/180);updateHud();if(distance>=GOAL){win();return}if(tutorialIndex<tutorialSteps.length){tutorialDelay-=dt;if(!tutorialObstacle&&tutorialDelay<=0)spawnTutorial()}else{spawnTimer-=dt;if(spawnTimer<=0){spawnPattern();spawnTimer=Math.max(.95,2.2-distance/1800*.7)}}for(const o of obstacles){o.z-=speed*dt*1.65;o.phase+=dt*4;if(o.tutorial&&o===tutorialObstacle&&o.z<34&&!tutorialPaused)showTutorial(tutorialSteps[tutorialIndex].action);if(!o.hit&&o.z<5&&o.z>-4&&!safeAgainst(o))hit(o)}obstacles=obstacles.filter(o=>o.z>-12)}

function seeded(i){const x=Math.sin(i*127.13+19.71)*43758.5453;return x-Math.floor(x)}
function mountainPath(base,amp,step,offset){ctx.beginPath();ctx.moveTo(0,h);for(let x=0;x<=w+step;x+=step){const n=seeded(Math.floor(x/step)+offset),n2=seeded(Math.floor(x/step)+offset+41);ctx.lineTo(x,base-amp*(.25+n*.55+n2*.2))}ctx.lineTo(w,h);ctx.closePath()}
function drawPalm(x,y,s,alpha){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#314625';ctx.lineWidth=Math.max(2,s*.12);ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+s*.12,y-s*.9,x-s*.02,y-s*1.7);ctx.stroke();ctx.translate(x-s*.02,y-s*1.7);ctx.strokeStyle='#3e6d31';ctx.lineWidth=Math.max(1,s*.055);for(let i=0;i<8;i++){const a=(i/8)*Math.PI*2+Math.sin(time*.25+x)*.04;ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo(Math.cos(a)*s*.45,Math.sin(a)*s*.18,Math.cos(a)*s*.82,Math.sin(a)*s*.38);ctx.stroke()}ctx.restore()}
function drawCactus(x,y,s,alpha){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#6a8e43';ctx.lineCap='round';ctx.lineWidth=s*.25;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-s*1.3);ctx.moveTo(x,y-s*.65);ctx.lineTo(x-s*.35,y-s*.82);ctx.lineTo(x-s*.35,y-s*1.03);ctx.moveTo(x,y-s*.85);ctx.lineTo(x+s*.35,y-s*1.02);ctx.lineTo(x+s*.35,y-s*1.22);ctx.stroke();ctx.restore()}
function drawProceduralBackground(){const blend=Math.max(0,Math.min(1,(distance-900)/700));const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,blend>.5?'#49a8d2':'#2596cf');sky.addColorStop(.52,blend>.5?'#d9bf82':'#8ecbc3');sky.addColorStop(1,blend>.5?'#e5b86a':'#315e3f');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.86;ctx.fillStyle=blend>.5?'#fff0b0':'#fff6c4';ctx.beginPath();ctx.arc(w*.76,h*.14,w*.095,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
  mountainPath(h*.48,h*.22,48,7);ctx.fillStyle=blend>.5?'#8e6048':'#456d62';ctx.fill();mountainPath(h*.54,h*.16,38,61);ctx.fillStyle=blend>.5?'#b17b50':'#3e6652';ctx.fill();mountainPath(h*.62,h*.11,30,121);ctx.fillStyle=blend>.5?'#c99a62':'#315a43';ctx.fill();
  const horizon=h*.31;for(let i=0;i<20;i++){const p=(i/20+distance*.0018)%1,y=horizon+Math.pow(p,1.45)*h*.69,s=10+Math.pow(p,1.3)*70,side=i%2?-1:1,x=w/2+side*(trackAt(p).half+s*(.45+seeded(i)*.45));if(blend<.65)drawPalm(x,y,s,Math.max(.15,1-blend*.8));if(blend>.25)drawCactus(x,y,s*.72,Math.max(.1,(blend-.2)*1.15))}
  const vignette=ctx.createRadialGradient(w/2,h*.48,w*.18,w/2,h*.52,w*.78);vignette.addColorStop(0,'rgba(0,0,0,0)');vignette.addColorStop(1,'rgba(0,10,7,.32)');ctx.fillStyle=vignette;ctx.fillRect(0,0,w,h);visualDebug.background={procedural:true,blend:+blend.toFixed(2),backingWidth:canvas.width,backingHeight:canvas.height,dpr}
}
function trackPoint(p,nx){const m=trackAt(p),y=h*.31+Math.pow(p,1.43)*h*.635;return{x:w/2+m.half*nx,y}}
function drawTrack(){const center=w/2,horizon=h*.31,bottom=h*.992,topHalf=trackAt(0).half,bottomHalf=trackAt(1).half;ctx.save();ctx.beginPath();ctx.moveTo(center-topHalf,horizon);ctx.lineTo(center+topHalf,horizon);ctx.lineTo(center+bottomHalf,bottom);ctx.lineTo(center-bottomHalf,bottom);ctx.closePath();const blend=Math.max(0,Math.min(1,(distance-900)/700)),g=ctx.createLinearGradient(0,horizon,0,bottom);g.addColorStop(0,blend>.5?'rgba(180,119,55,.76)':'rgba(83,58,32,.76)');g.addColorStop(1,blend>.5?'rgba(236,180,86,.97)':'rgba(125,83,43,.97)');ctx.fillStyle=g;ctx.fill();ctx.clip();for(let i=0;i<28;i++){const p=(i/28+distance*.016)%1,p2=Math.min(1,p+.016),y1=trackPoint(p,0).y,y2=trackPoint(p2,0).y;ctx.fillStyle=i%2?'rgba(255,255,255,.035)':'rgba(35,20,10,.06)';ctx.fillRect(0,y1,w,Math.max(1,y2-y1))}ctx.restore();const dashOffset=-(distance*1.7%40);for(const boundary of[-1/3,1/3]){ctx.save();ctx.strokeStyle='rgba(255,239,178,.78)';ctx.lineWidth=Math.max(1.7,w*.005);ctx.setLineDash([Math.max(8,h*.025),Math.max(8,h*.021)]);ctx.lineDashOffset=dashOffset;ctx.beginPath();for(let i=0;i<=32;i++){const p=i/32,pt=trackPoint(p,boundary);i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y)}ctx.stroke();ctx.restore()}for(const edge of[-1,1]){ctx.strokeStyle='rgba(201,244,123,.55)';ctx.lineWidth=Math.max(2,w*.007);ctx.beginPath();for(let i=0;i<=32;i++){const p=i/32,pt=trackPoint(p,edge);i?ctx.lineTo(pt.x,pt.y):ctx.moveTo(pt.x,pt.y)}ctx.stroke()}visualDebug.track={horizonY:horizon,bottomY:bottom,topWidth:topHalf*2,bottomWidth:bottomHalf*2,laneWidth:bottomHalf*2/3,laneCenters:[center-bottomHalf*2/3,center,center+bottomHalf*2/3],dashOffset:+dashOffset.toFixed(2),dashDirection:'toward-player'}}
function drawLegacy(name,x,y,targetWidth,opts={}){const r=SPRITES[name],im=images.atlas,dw=targetWidth,baseDh=CELL_H*(targetWidth/CELL_W),dh=baseDh*(opts.scaleY??1);ctx.save();ctx.translate(x,y);if(opts.rotate)ctx.rotate(opts.rotate);if(opts.alpha!==undefined)ctx.globalAlpha=opts.alpha;if(opts.shadow)ctx.filter='drop-shadow(0 8px 8px rgba(0,0,0,.4))';const anchorY=opts.anchorY??.95;ctx.drawImage(im,r[0]*ATLAS_SCALE,r[1]*ATLAS_SCALE,r[2]*ATLAS_SCALE,r[3]*ATLAS_SCALE,-dw/2,-dh*anchorY,dw,dh);ctx.restore();ctx.filter='none';ctx.globalAlpha=1;return{x:x-dw/2,y:y-dh*anchorY,width:dw,height:dh,source:name}}
function drawFlightAsset(name,x,y,targetWidth,opts={}){const im=images[name],dw=targetWidth,dh=targetWidth*(im.height/im.width);ctx.save();ctx.translate(x,y);if(opts.alpha!==undefined)ctx.globalAlpha=opts.alpha;if(opts.shadow)ctx.filter='drop-shadow(0 8px 8px rgba(0,0,0,.36))';const anchorY=opts.anchorY??.52;ctx.drawImage(im,-dw/2,-dh*anchorY,dw,dh);ctx.restore();ctx.filter='none';ctx.globalAlpha=1;return{x:x-dw/2,y:y-dh*anchorY,width:dw,height:dh}}
function drawShadow(x,y,width,alpha=.2){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle='#08120c';ctx.beginPath();ctx.ellipse(x,y,width/2,Math.max(3,width*.075),0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawSideCue(x,y,laneWidth,alpha=.2){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle='#ff7a3d';ctx.beginPath();ctx.ellipse(x,y-3,laneWidth*.48,Math.max(4,laneWidth*.075),0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,236,171,.85)';ctx.lineWidth=Math.max(1.5,laneWidth*.018);for(const dir of[-1,1]){const cx=x+dir*laneWidth*.26;ctx.beginPath();ctx.moveTo(cx-dir*laneWidth*.08,y-8);ctx.lineTo(cx,y-3);ctx.lineTo(cx-dir*laneWidth*.08,y+2);ctx.stroke()}ctx.restore()}
function drawWorld(){visualDebug.obstacles=[];visualDebug.ptero=null;for(const o of[...obstacles].sort((a,b)=>b.z-a.z)){const p=perspective(o.z),x=w/2+o.lane*p.laneX,def=obstacleDefs[o.type],hitAlpha=o.hit?.45:1;if(o.type==='ptero'){const target=p.laneWidth*def.width,lift=130+p.laneWidth*1.18,bob=Math.sin(time*5.5+o.phase)*Math.max(1.5,p.laneWidth*.025),cy=p.y-lift+bob,wingPhase=time*PTERO_BLEND_SPEED+o.phase,mix=(Math.sin(wingPhase)+1)/2;drawShadow(x,p.y+2,p.laneWidth*.36,.12);const rect0=drawFlightAsset('ptero0',x,cy,target,{anchorY:.5,shadow:true,alpha:hitAlpha*(1-mix)}),rect1=drawFlightAsset('ptero1',x,cy,target,{anchorY:.5,shadow:true,alpha:hitAlpha*mix}),rect={x:rect0.x,y:rect0.y,width:rect0.width,height:rect0.height};visualDebug.ptero={frame:'smooth-blend',sources:['ptero0','ptero1'],mix:+mix.toFixed(3),alphaTotal:+((1-mix)+mix).toFixed(3),groundY:+p.y.toFixed(1),centerY:+cy.toFixed(1),bottomY:+(rect.y+rect.height).toFixed(1),bottomClearance:+(p.y-(rect.y+rect.height)).toFixed(1),rect,laneWidth:+p.laneWidth.toFixed(1),lane:o.lane};visualDebug.obstacles.push({type:o.type,action:def.action,lane:o.lane,rect,laneWidth:+p.laneWidth.toFixed(1),ratio:+(rect.width/p.laneWidth).toFixed(2),visualHeight:+rect.height.toFixed(1),source:'ptero0+ptero1'});continue}let target=p.laneWidth*def.width,drawX=x,drawY=p.y,rotation=0,source=def.sprite;if(def.action==='side')drawSideCue(x,p.y,p.laneWidth,o.hit?.08:.22);if(o.type==='trex'){const gait=time*5.2+o.phase,step=Math.sin(gait);drawX+=step*p.laneWidth*.035;drawY-=Math.abs(Math.cos(gait))*p.laneWidth*.025;rotation=step*.018;target*=1+Math.cos(gait*2)*.018;source='trex'}drawShadow(x,p.y+1,p.laneWidth*(o.type==='trex'?.76:.58),o.type==='trex'?.3:.18);const rect=drawLegacy(source,drawX,drawY,target,{anchorY:.95,shadow:true,alpha:hitAlpha,scaleY:def.heightScale??1,rotate:rotation});visualDebug.obstacles.push({type:o.type,action:def.action,lane:o.lane,rect,laneWidth:+p.laneWidth.toFixed(1),ratio:+(rect.width/p.laneWidth).toFixed(2),visualHeight:+rect.height.toFixed(1),source,animation:o.type==='trex'?'procedural-single-source':'static'})}}
function playerImage(){if(player.hurt>0)return'hurt';if(player.slide>0)return'slide';if(player.y>.05)return'jump';if(player.turnTimer>0)return player.turnDir<0?'turn_left':'turn_right';return`run${Math.floor(time*11)%4+1}`}
function drawPlayer(){if(player.invuln>0&&Math.floor(player.invuln*12)%2===0){visualDebug.player=null;return}const vs=Math.min(w/390,h/844),near=trackAt(1),baseX=w/2+player.x*near.laneCenter,baseY=h*.925-player.y*h*.18;let sc=vs*.99;if(player.y>.05)sc*=1.02;if(player.slide>0)sc*=.98;const rf=Math.floor(time*11)%4,bob=player.y>0||player.slide>0||player.hurt>0||player.turnTimer>0?0:[0,-3,1,-2][rf]*vs,[col,row]=PLAYER_CELLS[playerImage()],dw=PLAYER_CELL*sc,dh=PLAYER_CELL*sc,rect={x:baseX-dw/2,y:baseY+bob-dh*.97,width:dw,height:dh};ctx.save();ctx.translate(baseX,baseY+bob);ctx.filter='drop-shadow(0 9px 9px rgba(0,0,0,.42))';ctx.drawImage(images.player,col*PLAYER_CELL,row*PLAYER_CELL,PLAYER_CELL,PLAYER_CELL,-dw/2,-dh*.97,dw,dh);ctx.restore();ctx.filter='none';visualDebug.player={rect,baseY:+baseY.toFixed(1),jumpY:+player.y.toFixed(3),frame:playerImage()}}
function draw(){resize();ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake*.55);drawProceduralBackground();drawTrack();drawWorld();drawPlayer();ctx.restore()}
function frame(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;if(state==='home')time+=dt*.35;update(dt);draw();requestAnimationFrame(frame)}

let pointer=null;canvas.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY};try{canvas.setPointerCapture(e.pointerId)}catch(_){}});canvas.addEventListener('pointerup',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,ax=Math.abs(dx),ay=Math.abs(dy);pointer=null;if(state==='home'){start();return}if(Math.max(ax,ay)<24){act('up');return}act(ax>ay?(dx>0?'right':'left'):(dy>0?'down':'up'))});canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft'||e.key==='a')act('left');else if(e.key==='ArrowRight'||e.key==='d')act('right');else if(e.key==='ArrowUp'||e.key==='w'||e.key===' ')act('up');else if(e.key==='ArrowDown'||e.key==='s')act('down');else if(e.key==='p'||e.key==='Escape')state==='paused'?resume():pause()});
$('start-btn').onclick=start;$('pause-btn').onclick=pause;$('resume-btn').onclick=resume;$('restart-pause').onclick=start;$('restart-btn').onclick=start;$('home-btn').onclick=home;$('win-restart').onclick=start;$('win-home').onclick=home;addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause()});
window.__RAPTOR_GAME__={get rules(){return Object.fromEntries(Object.entries(obstacleDefs).map(([type,d])=>[type,{action:d.action,width:d.width,heightScale:d.heightScale??1}]))},get state(){return state},get stats(){return{distance:Math.floor(distance),lives,lane:player.lane,y:+player.y.toFixed(2),sliding:player.slide>0,playerFrame:playerImage(),tutorialIndex,obstacles:obstacles.map(o=>({type:o.type,lane:o.lane,z:+o.z.toFixed(1)}))}},get visual(){return JSON.parse(JSON.stringify(visualDebug))},get assets(){return Object.fromEntries(Object.entries(images).map(([k,v])=>[k,{width:v.naturalWidth,height:v.naturalHeight}]))},start,left:()=>act('left'),right:()=>act('right'),jump:()=>act('up'),slide:()=>act('down'),pause,resume,home,forceDamage(){hit({hit:false})},forceGoal(){distance=GOAL-1},skipTutorial(){tutorialIndex=tutorialSteps.length;tutorialObstacle=null;obstacles=[];spawnTimer=99;hideTutorial();if(state==='tutorial')state='running'},clear(){obstacles=[];spawnTimer=99},forceObstacle(type='boulder',lane=0,z=18){obstacles.push({type,lane,z,hit:false,phase:0})}};
resize();loadAssets().then(()=>{ui.loading.classList.remove('visible');setState('home');requestAnimationFrame(frame)}).catch(err=>{console.error(err);ui.loading.querySelector('strong').textContent='ERROR AL CARGAR ASSETS'});
})();
